import { Inter, Zalando_Sans_Expanded } from "next/font/google";
import "./globals.css";
import Footer from "@/components/shared/Footer";
import Navbar from "@/components/shared/Navbar";

const montserrat = Zalando_Sans_Expanded({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata = {
  title: "Cormep Event Marketing",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased`}>{children}</body>
    </html>
  );
}
