import { Zalando_Sans_Expanded } from "next/font/google";
import "./globals.css";

const montserrat = Zalando_Sans_Expanded({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata = {
  title: "Cormep Event Marketing",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="apple-touch-icon" href="/images/icon.svg"></link>
        <link rel="shortcut icon" href="/images/icon.svg"></link>
      </head>
      <body className={`${montserrat.variable} antialiased`}>{children}</body>
    </html>
  );
}
